// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelGeneration(arg1:string):Promise<void>;

export function ChooseImages():Promise<Array<main.Attachment>>;

export function CreateConversation():Promise<main.Conversation>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GetConversation(arg1:string):Promise<main.Conversation>;

export function GetModelStatus():Promise<main.ModelStatus>;

export function GetUserAvatar():Promise<string>;

export function ListConversations():Promise<Array<main.Conversation>>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<main.Attachment>):Promise<main.Message>;
