// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGeneration(arg1) {
  return window['go']['main']['App']['CancelGeneration'](arg1);
}

export function ChooseImages() {
  return window['go']['main']['App']['ChooseImages']();
}

export function CreateConversation() {
  return window['go']['main']['App']['CreateConversation']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetModelStatus() {
  return window['go']['main']['App']['GetModelStatus']();
}

export function GetUserAvatar() {
  return window['go']['main']['App']['GetUserAvatar']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}
